/**
 * @Author:     Parsa Rajabi
 * @Created:    2021.02.04
 *
 * @Description: Constants for Classifieds
 *
 */

import {
    BUSINESS_CLASSIFIEDS_CATEGORIES,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES,
    HOUSE_YARD_SERVICES_SUBCATEGORIES,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES,
    RENTALS_SUBCATEGORIES
} from "./classifiedListingText";

export const BUSINESS_CLASSIFIEDS_CATEGORIES_DROPDOWN = [
    {
        label: BUSINESS_CLASSIFIEDS_CATEGORIES.RENTALS,
        value: BUSINESS_CLASSIFIEDS_CATEGORIES.RENTALS
    },
    {
        label: BUSINESS_CLASSIFIEDS_CATEGORIES.HOUSE_YARD,
        value: BUSINESS_CLASSIFIEDS_CATEGORIES.HOUSE_YARD
    }, {
        label: BUSINESS_CLASSIFIEDS_CATEGORIES.LEGAL_SALES,
        value: BUSINESS_CLASSIFIEDS_CATEGORIES.LEGAL_SALES
    }, {
        label: BUSINESS_CLASSIFIEDS_CATEGORIES.CLASSES_CLUBS,
        value: BUSINESS_CLASSIFIEDS_CATEGORIES.CLASSES_CLUBS
    },
]

export const RENTALS_SUBCATEGORIES_LIST = [
    RENTALS_SUBCATEGORIES.HOUSE,
    RENTALS_SUBCATEGORIES.PARTIAL_HOUSE,
    RENTALS_SUBCATEGORIES.DUPLEX,
    RENTALS_SUBCATEGORIES.APART,
    RENTALS_SUBCATEGORIES.CONDO,
    RENTALS_SUBCATEGORIES.RURAL,
    RENTALS_SUBCATEGORIES.COUNTRY,
    RENTALS_SUBCATEGORIES.OTHER,
]

export const HOUSE_YARD_SERVICES_SUBCATEGORIES_LIST = [
    HOUSE_YARD_SERVICES_SUBCATEGORIES.CLEAN_CARPET,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.COMPUTER_TECH,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.DELIVERY,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.DUCT_CLEANING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.GARDENING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HANDYMAN,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOUSE_KEEPER,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOME_CARE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOUSE_MAINTENANCE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.MEAL_SERVICE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.MOVING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.ORGANIZING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.PET,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.RIDE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.CLEAN_WINDOW,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.OTHER,
]

export const LEGAL_SALES_AGENCIES_SUBCATEGORIES_LIST = [
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.LEGALITIES,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.REALTORS,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.MULTI_SHARE_HOME,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.SHARE_CARE,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.TAX,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.MULTI_TENANT,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.SHARED_HOME,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.OTHER,
]


export const CLASSES_CLUBS_EVENTS_SUBCATEGORIES_LIST = [
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.CLASSES,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.EVENTS,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.EXERCISE,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.CLUBS,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.OTHER,
]