/**
 * @Author:     Parsa Rajabi
 * @Created:    2021.02.04
 *
 * @Description: Constants for Services
 *
 */

import {
    MEMBER_SERVICE_CATEGORIES,
    BUSINESS_SERVICE_CATEGORIES,
    CO_HOUSING_SUBCATEGORIES,
    SHARED_HOME_SERVICES_SUBCATEGORIES,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES,
    GOVERNMENT_SERVICES_SUBCATEGORIES
} from "./serviceListingText";

export const MEMBER_SERVICE_CATEGORIES_DROPDOWN = [
    {
        label: MEMBER_SERVICE_CATEGORIES.MEMBER_HOME,
        value: MEMBER_SERVICE_CATEGORIES.MEMBER_HOME
    }
]


export const BUSINESS_SERVICE_CATEGORIES_DROPDOWN = [
    {
        label: BUSINESS_SERVICE_CATEGORIES.CO_HOUSING,
        value: BUSINESS_SERVICE_CATEGORIES.CO_HOUSING,
    },
    {
        label: BUSINESS_SERVICE_CATEGORIES.SHARED_HOME_SERVICES,
        value: BUSINESS_SERVICE_CATEGORIES.SHARED_HOME_SERVICES,
    },
    {
        label: BUSINESS_SERVICE_CATEGORIES.SHARED_BUSINESS_SERVICES,
        value: BUSINESS_SERVICE_CATEGORIES.SHARED_BUSINESS_SERVICES,
    },
    {
        label: BUSINESS_SERVICE_CATEGORIES.GOVERNMENT_SERVICES,
        value: BUSINESS_SERVICE_CATEGORIES.GOVERNMENT_SERVICES,
    },
]

export const CO_HOUSING_SUBCATEGORIES_LIST = [
    CO_HOUSING_SUBCATEGORIES.CO_HOUSING,
    CO_HOUSING_SUBCATEGORIES.CO_OP,
    CO_HOUSING_SUBCATEGORIES.COMMUNAL,
    CO_HOUSING_SUBCATEGORIES.ECO,
    CO_HOUSING_SUBCATEGORIES.INTER_GEN,
    CO_HOUSING_SUBCATEGORIES.SHARED_LIVING,
    CO_HOUSING_SUBCATEGORIES.OTHER,
]

export const SHARED_HOME_SERVICES_SUBCATEGORIES_LIST = [
    SHARED_HOME_SERVICES_SUBCATEGORIES.MEET_UPS,
    SHARED_HOME_SERVICES_SUBCATEGORIES.WORKSHOPS,
    SHARED_HOME_SERVICES_SUBCATEGORIES.CLASSES,
    SHARED_HOME_SERVICES_SUBCATEGORIES.OTHER,
]

export const SHARED_BUSINESS_SERVICES_SUBCATEGORIES_LIST = [
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.GROUPS_ORG,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.COMPANION_FINDING,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.DATING,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.DATING_ED,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.OTHER,
]

export const GOVERNMENT_SERVICES_SUBCATEGORIES_LIST = [
    GOVERNMENT_SERVICES_SUBCATEGORIES.SENIORS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.LOW_INCOME,
    GOVERNMENT_SERVICES_SUBCATEGORIES.YOUTHS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.HOMELESS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.INDIVIDUALS_GROUPS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.HOME_CARE,
    GOVERNMENT_SERVICES_SUBCATEGORIES.OTHER,
]