/**
 * @Author:     Parsa Rajabi
 * @Created:    2021.02.04
 *
 * @Description: Constants for Services
 *
 */

import {
    MEMBER_SERVICE_CATEGORIES,
    MEMBER_HOME_SHARE_SUBCATEGORIES,
    BUSINESS_SERVICE_CATEGORIES,
    SHARED_COMMUNITY_SUBCATEGORIES,
    SHARED_SERVICES_SUBCATEGORIES,
    GOVERNMENT_SERVICES_SUBCATEGORIES
} from "./serviceListingText";

export const MEMBER_SERVICE_CATEGORIES_DROPDOWN = [
    {
        label: MEMBER_SERVICE_CATEGORIES.MEMBER_HOME,
        value: MEMBER_SERVICE_CATEGORIES.MEMBER_HOME
    }
]

export const MEMBER_HOME_SHARE_SUBCATEGORIES_LIST = [
    MEMBER_HOME_SHARE_SUBCATEGORIES.CITY,
    MEMBER_HOME_SHARE_SUBCATEGORIES.TOWN_VILLAGE,
    MEMBER_HOME_SHARE_SUBCATEGORIES.RURAL,
    MEMBER_HOME_SHARE_SUBCATEGORIES.COUNTRY_REMOTE,
    MEMBER_HOME_SHARE_SUBCATEGORIES.OTHER,
]

export const BUSINESS_SERVICE_CATEGORIES_DROPDOWN = [
    {
        label: BUSINESS_SERVICE_CATEGORIES.SHARE_COMMUNITY,
        value: BUSINESS_SERVICE_CATEGORIES.SHARE_COMMUNITY,
    },
    {
        label: BUSINESS_SERVICE_CATEGORIES.SHARED_SERVICES,
        value: BUSINESS_SERVICE_CATEGORIES.SHARED_SERVICES,
    },
    {
        label: BUSINESS_SERVICE_CATEGORIES.GOVERNMENT_SERVICES,
        value: BUSINESS_SERVICE_CATEGORIES.GOVERNMENT_SERVICES,
    },
]

export const SHARED_COMMUNITY_SUBCATEGORIES_LIST = [
    SHARED_COMMUNITY_SUBCATEGORIES.CO_HOUSING,
    SHARED_COMMUNITY_SUBCATEGORIES.CO_OP,
    SHARED_COMMUNITY_SUBCATEGORIES.COMMUNAL,
    SHARED_COMMUNITY_SUBCATEGORIES.ECO,
    SHARED_COMMUNITY_SUBCATEGORIES.INTER_GEN,
    SHARED_COMMUNITY_SUBCATEGORIES.SHARED_LIVING,
    SHARED_COMMUNITY_SUBCATEGORIES.OTHER,
]

export const SHARED_SERVICES_SUBCATEGORIES_LIST = [
    SHARED_SERVICES_SUBCATEGORIES.GROUP_MEET_UPS,
    SHARED_SERVICES_SUBCATEGORIES.SENIOR_MEET_UPS,
    SHARED_SERVICES_SUBCATEGORIES.SINGLE_PARENT,
    SHARED_SERVICES_SUBCATEGORIES.MEMBER_INITIATED,
    SHARED_SERVICES_SUBCATEGORIES.HOME_CONTRACT,
    SHARED_SERVICES_SUBCATEGORIES.HOME_SERVICES,
    SHARED_SERVICES_SUBCATEGORIES.STUDENT,
    SHARED_SERVICES_SUBCATEGORIES.NEGOTIATION,
    SHARED_SERVICES_SUBCATEGORIES.CONFLICT,
    SHARED_SERVICES_SUBCATEGORIES.ONLINE,
    SHARED_SERVICES_SUBCATEGORIES.HOW_TO,
    SHARED_SERVICES_SUBCATEGORIES.INSURANCE,
    SHARED_SERVICES_SUBCATEGORIES.OTHER,
]

export const GOVERNMENT_SERVICES_SUBCATEGORIES_LIST = [
    GOVERNMENT_SERVICES_SUBCATEGORIES.HOUSING_FIRST,
    GOVERNMENT_SERVICES_SUBCATEGORIES.LOW_INCOME,
    GOVERNMENT_SERVICES_SUBCATEGORIES.SENIOR_HOME,
    GOVERNMENT_SERVICES_SUBCATEGORIES.SPECIAL_NEEDS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.OTHER,
]