/**
 * @Author:     Rachelle Gelden
 * @Created:    2021.05.17
 *
 * @Description: model for profileBookmark table. This table contains all members' bookmarked profiles
 *
 */

module.exports = (DataTypes, sequelize) => {
    // MemberAccountUid and BookmarkedProfileUid columns are automatically generated by seqeulize as foreign keys
    return sequelize.define('ProfileBookmark', {},
        {
            createdAt: 'dateBookmarked'
        }
    );
}
