export const businessUser = {
    logo: null,
    businessName : "Sal's Homesharing Service",
    username : "BigApple",
    email: "sal@homesharing.com",
    hasDifferentMailingAddress : true,
    isIncorporated : true,
    incorporatedOwnersNames : "Bob",
    isNationWide : false,
    website : "www.bigApple.com",
    firstName: "Jack",
    lastName: "Lee",
    businessPhoneNumber : "778-821-5555",
    businessCellPhoneNumber : "250-666-8888",
    phoneNumber : "778-565-6565",
    addressLine1: "766 Rutland Rd. S.",
    addressLine2: "#9",
    city: "Kelowna",
    province: "BC",
    postalCode: "V1X 5B5",
    mailingAddressLine1: "333 Rd",
    mailingAddressLine2: "#3",
    mailingCity: "Fat Rose",
    mailingProvince: "BC",
    mailingPostalCode: "V1X 3B3",
    mapAddressLine1: "555 haha Rd",
    mapAddressLine2: "#5",
    mapCity: "Cool Jack",
    mapPostalCode: "BC",
    mapProvince: "V1X 5B5",
    password:"Password123"
}
