/**
 * @Author:     Rachelle Gelden
 * @Created:    2021.02.20
 *
 * @Description: constants for service and classified categories and subcategories
 *
 */

const LISTING_TYPES = {
    SERVICE: 'service',
    CLASSIFIED: 'classified'
}

const BUSINESS_SERVICES_CATEGORIES = {
    CO_HOUSING: 'Co-housing, Co-ops, Intergenerational & Planned Neighbourhoods',
    SHARED_HOME_SERVICES: "Home Share Facilitation & Supporting Services",
    SHARED_BUSINESS_SERVICES: "Home Sharing Businesses, Groups and Organizations",
    GOVERNMENT_SERVICES: "Government & Human Service Agencies Offering Shared Living & Support Services"
}

const MEMBER_SERVICE_CATEGORIES = {
    MEMBER_HOME: "Members with Homes to Share",
}

const CO_HOUSING_SUBCATEGORIES = {
    CO_HOUSING: "Co-housing Groups & Communities",
    CO_OP: "Cooperatives",
    COMMUNAL: "Communal Living",
    ECO: "Eco villages",
    INTER_GEN: "Intergenerational Living",
    SHARED_LIVING: "Shared Living First Step Homes",
    OTHER: "Other"
}

const SHARED_HOME_SERVICES_SUBCATEGORIES = {
    MEET_UPS: "Home Share Meet-ups & Get-togethers",
    WORKSHOPS: "Seminars and Workshops: (Shared and Companion Living)",
    CLASSES: "Home Share Classes: contracts, agreements, negotiation etc.",
    OTHER: "Other"
}

const SHARED_BUSINESS_SERVICES_SUBCATEGORIES = {
    GROUPS_ORG: "Home Sharing Groups and Organizations",
    COMPANION_FINDING: "Home & Companion Finding/Matching Businesses",
    DATING: "Home & Companion Matching Businesses",
    DATING_ED: "Home & Companion Educational Program Providers",
    OTHER: "Other"
}

const GOVERNMENT_SERVICES_SUBCATEGORIES = {
    SENIORS: "Agencies serving Seniors",
    LOW_INCOME: "Agencies Addressing Low Income Housing",
    YOUTHS: "Agencies Serving Youth",
    HOMELESS: "Agencies Serving the Homeless",
    INDIVIDUALS_GROUPS: "Agencies Serving Other Individuals and Groups",
    HOME_CARE: "Home Care Agencies",
    OTHER: "Other"
}

const BUSINESS_CLASSIFIEDS_CATEGORIES = {
    RENTALS: "Rentals",
    HOUSE_YARD: "House & Yard Services",
    LEGAL_SALES: "Legal & Sales",
    CLASSES_CLUBS: "Classes, Clubs & Events",
}

const RENTALS_SUBCATEGORIES = {
    HOUSE: "House",
    PARTIAL_HOUSE: "Partial house / suite up or down",
    DUPLEX: "Duplex / triplex",
    APART: "Apartment",
    CONDO: "Condo/townhouse",
    RURAL: "Rural",
    COUNTRY: "Country",
    OTHER: "Other"
}

const HOUSE_YARD_SERVICES_SUBCATEGORIES = {
    CLEAN_CARPET: "Carpet Cleaning",
    COMPUTER_TECH: "Computer & Technical Services",
    DELIVERY: "Delivery Services",
    DUCT_CLEANING: "Duct Cleaning",
    GARDENING: "Gardening, Yard Work & Yard Maintenance",
    HANDYMAN: "Handyman Services",
    HOUSE_KEEPER: "Housekeeper/Cleaner",
    HOME_CARE: "Home Care Services",
    HOUSE_MAINTENANCE: "House Maintenance & Repair",
    MEAL_SERVICE: "Meal Services",
    MOVING: "Moving & Storage",
    ORGANIZING: "Organizing/De-cluttering",
    PET: "Pet Services",
    RIDE: "Ride Sharing & Transportation",
    CLEAN_WINDOW: "Window Cleaning",
    OTHER: "Other"
}

const LEGAL_SALES_AGENCIES_SUBCATEGORIES = {
    LEGALITIES: "Multi-Ownership Purchasing: Legalities",
    REALTORS: "Multi-Ownership Purchasing: Realtors",
    MULTI_SHARE_HOME: "Multi-Ownership/Tenant/Shared Home Insurance",
    SHARE_CARE: "Shared Vehicle Insurance & Legalities",
    TAX: "Understanding Home Sharing & Taxes",
    MULTI_TENANT: "Multi-Tenant Rentals and Leases",
    SHARED_HOME: "Shared Homes A-Z",
    OTHER: "Other"
}

const CLASSES_CLUBS_EVENTS_SUBCATEGORIES = {
    CLASSES: "Classes & Lessons (Art, Music, Computer, Cooking, Language, etc)",
    EVENTS: "Events & Activities (Paint-night, Art Show, Wine Tasting, Concert, etc)",
    EXERCISE: "Exercise Classes (Yoga, Pilates, Walking, Running, etc.)",
    CLUBS: "Groups & Clubs (Computer, Bird Watching, Book Club, Singing, etc)",
    OTHER: "Other"
}

const CO_HOUSING_SUBCATEGORIES_ARRAY = [
    CO_HOUSING_SUBCATEGORIES.CO_HOUSING,
    CO_HOUSING_SUBCATEGORIES.CO_OP,
    CO_HOUSING_SUBCATEGORIES.COMMUNAL,
    CO_HOUSING_SUBCATEGORIES.ECO,
    CO_HOUSING_SUBCATEGORIES.INTER_GEN,
    CO_HOUSING_SUBCATEGORIES.SHARED_LIVING,
    CO_HOUSING_SUBCATEGORIES.OTHER,
]

const SHARED_HOME_SERVICES_SUBCATEGORIES_ARRAY = [
    SHARED_HOME_SERVICES_SUBCATEGORIES.MEET_UPS,
    SHARED_HOME_SERVICES_SUBCATEGORIES.WORKSHOPS,
    SHARED_HOME_SERVICES_SUBCATEGORIES.CLASSES,
    SHARED_HOME_SERVICES_SUBCATEGORIES.OTHER,
]

const SHARED_BUSINESS_SERVICES_SUBCATEGORIES_ARRAY = [
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.GROUPS_ORG,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.COMPANION_FINDING,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.DATING,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.DATING_ED,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES.OTHER,
]

const GOVERNMENT_SERVICES_SUBCATEGORIES_ARRAY = [
    GOVERNMENT_SERVICES_SUBCATEGORIES.SENIORS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.LOW_INCOME,
    GOVERNMENT_SERVICES_SUBCATEGORIES.YOUTHS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.HOMELESS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.INDIVIDUALS_GROUPS,
    GOVERNMENT_SERVICES_SUBCATEGORIES.HOME_CARE,
    GOVERNMENT_SERVICES_SUBCATEGORIES.OTHER,
]

const RENTALS_SUBCATEGORIES_ARRAY = [
    RENTALS_SUBCATEGORIES.HOUSE,
    RENTALS_SUBCATEGORIES.PARTIAL_HOUSE,
    RENTALS_SUBCATEGORIES.DUPLEX,
    RENTALS_SUBCATEGORIES.APART,
    RENTALS_SUBCATEGORIES.CONDO,
    RENTALS_SUBCATEGORIES.RURAL,
    RENTALS_SUBCATEGORIES.COUNTRY,
    RENTALS_SUBCATEGORIES.OTHER,
]

const HOUSE_YARD_SERVICES_SUBCATEGORIES_ARRAY = [
    HOUSE_YARD_SERVICES_SUBCATEGORIES.CLEAN_CARPET,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.COMPUTER_TECH,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.DELIVERY,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.DUCT_CLEANING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.GARDENING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HANDYMAN,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOUSE_KEEPER,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOME_CARE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.HOUSE_MAINTENANCE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.MEAL_SERVICE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.MOVING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.ORGANIZING,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.PET,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.RIDE,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.CLEAN_WINDOW,
    HOUSE_YARD_SERVICES_SUBCATEGORIES.OTHER,
]

const LEGAL_SALES_AGENCIES_SUBCATEGORIES_ARRAY = [
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.LEGALITIES,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.REALTORS,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.MULTI_SHARE_HOME,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.SHARE_CARE,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.TAX,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.MULTI_TENANT,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.SHARED_HOME,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES.OTHER,
]


const CLASSES_CLUBS_EVENTS_SUBCATEGORIES_ARRAY = [
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.CLASSES,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.EVENTS,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.EXERCISE,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.CLUBS,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES.OTHER,
]

const LISTING_CATEGORY_SUBCATEGORY_MAP = new Map([
    [BUSINESS_SERVICES_CATEGORIES.CO_HOUSING, CO_HOUSING_SUBCATEGORIES],
    [BUSINESS_SERVICES_CATEGORIES.SHARED_HOME_SERVICES, SHARED_HOME_SERVICES_SUBCATEGORIES],
    [BUSINESS_SERVICES_CATEGORIES.SHARED_BUSINESS_SERVICES, SHARED_BUSINESS_SERVICES_SUBCATEGORIES],
    [BUSINESS_SERVICES_CATEGORIES.GOVERNMENT_SERVICES, GOVERNMENT_SERVICES_SUBCATEGORIES],
    [BUSINESS_CLASSIFIEDS_CATEGORIES.RENTALS, RENTALS_SUBCATEGORIES],
    [BUSINESS_CLASSIFIEDS_CATEGORIES.HOUSE_YARD, HOUSE_YARD_SERVICES_SUBCATEGORIES],
    [BUSINESS_CLASSIFIEDS_CATEGORIES.LEGAL_SALES, LEGAL_SALES_AGENCIES_SUBCATEGORIES],
    [BUSINESS_CLASSIFIEDS_CATEGORIES.CLASSES_CLUBS, CLASSES_CLUBS_EVENTS_SUBCATEGORIES]
]);

const LISTING_IMAGE_UPLOADS_PATH = 'server/public/uploads/listings/';

module.exports = {
    LISTING_TYPES,
    BUSINESS_SERVICES_CATEGORIES,
    MEMBER_SERVICE_CATEGORIES,
    BUSINESS_CLASSIFIEDS_CATEGORIES,
    LISTING_CATEGORY_SUBCATEGORY_MAP,
    CO_HOUSING_SUBCATEGORIES,
    SHARED_HOME_SERVICES_SUBCATEGORIES,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES,
    GOVERNMENT_SERVICES_SUBCATEGORIES,
    RENTALS_SUBCATEGORIES,
    HOUSE_YARD_SERVICES_SUBCATEGORIES,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES,
    CO_HOUSING_SUBCATEGORIES_ARRAY,
    SHARED_HOME_SERVICES_SUBCATEGORIES_ARRAY,
    SHARED_BUSINESS_SERVICES_SUBCATEGORIES_ARRAY,
    GOVERNMENT_SERVICES_SUBCATEGORIES_ARRAY,
    RENTALS_SUBCATEGORIES_ARRAY,
    HOUSE_YARD_SERVICES_SUBCATEGORIES_ARRAY,
    LEGAL_SALES_AGENCIES_SUBCATEGORIES_ARRAY,
    CLASSES_CLUBS_EVENTS_SUBCATEGORIES_ARRAY,
    LISTING_IMAGE_UPLOADS_PATH
}
