/**
 * @Author:     Jeff Hatton
 * @Created:    2020.01.12
 *
 * @Description: Const array of mock profiles
 *
 */

const mockProfiles = [
    {
        username: "AliceinWonderLand",
        gender: "Female",
        birthYear: 1985,
        status: "Single",
        minMonthlyBudget: 200,
        maxMonthlyBudget: 550,
        hasPets: false,
        isSmoker: false,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "Babar",
        gender: "Male",
        birthYear: 1990,
        status: "Couple With Children",
        minMonthlyBudget: 2000,
        maxMonthlyBudget: 5500,
        hasPets: true,
        isSmoker: true,
        isReligionImportant: true,
        isDietImportant: true,
        hasHomeToShare: true
    },
    {
        username: "CREATINE",
        gender: "Other",
        birthYear: 1995,
        status: "Single",
        minMonthlyBudget: 800,
        maxMonthlyBudget: 1200,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: true,
        isDietImportant: true,
        hasHomeToShare: true
    },
    {
        username: "DonaldDuck",
        gender: "Male",
        birthYear: 1970,
        status: "Single Parent",
        minMonthlyBudget: 500,
        maxMonthlyBudget: 600,
        hasPets: false,
        isSmoker: false,
        isReligionImportant: true,
        isDietImportant: true,
        hasHomeToShare: true
    },
    {
        username: "EusticeOfNarnia",
        gender: "Male",
        birthYear: 1950,
        status: "Single",
        minMonthlyBudget: 1300,
        maxMonthlyBudget: 2300,
        hasPets: false,
        isSmoker: false,
        isReligionImportant: false,
        isDietImportant: true,
        hasHomeToShare: false
    },
    {
        username: "Foxtrot",
        gender: "Other",
        birthYear: 1980,
        status: "Couple",
        minMonthlyBudget: 1400,
        maxMonthlyBudget: 1600,
        hasPets: false,
        isSmoker: false,
        isReligionImportant: true,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Grinch",
        gender: "Other",
        birthYear: 1960,
        status: "Single",
        minMonthlyBudget: 2500,
        maxMonthlyBudget: 3700,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "Hydra",
        gender: "Female",
        birthYear: 1975,
        status: "Couple With Children",
        minMonthlyBudget: 1200,
        maxMonthlyBudget: 2550,
        hasPets: true,
        isSmoker: false,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "InnigoMontoya",
        gender: "Male",
        birthYear: 1970,
        status: "Single Parent",
        minMonthlyBudget: 300,
        maxMonthlyBudget: 575,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "JamesBond",
        gender: "Male",
        birthYear: 1950,
        status: "Single",
        minMonthlyBudget: 200,
        maxMonthlyBudget: 550,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: true,
        hasHomeToShare: false
    },
    {
        username: "Kirby",
        gender: "Other",
        birthYear: 1976,
        status: "Existing Group",
        minMonthlyBudget: 200,
        maxMonthlyBudget: 2550,
        hasPets: false,
        isSmoker: false,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "Link",
        gender: "Male",
        birthYear: 2001,
        status: "Couple",
        minMonthlyBudget: 500,
        maxMonthlyBudget: 700,
        hasPets: true,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Mario",
        gender: "Male",
        birthYear: 1950,
        status: "Single",
        minMonthlyBudget: 900,
        maxMonthlyBudget: 2600,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: true,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Nero",
        gender: "Male",
        birthYear: 1978,
        status: "Existing Group",
        minMonthlyBudget: 3300,
        maxMonthlyBudget: 6650,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "OddDuck",
        gender: "Female",
        birthYear: 1998,
        status: "Single",
        minMonthlyBudget: 400,
        maxMonthlyBudget: 1950,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: true,
        isDietImportant: true,
        hasHomeToShare: true
    },
    {
        username: "PlatoInPerson",
        gender: "Male",
        birthYear: 1950,
        status: "Single Parent",
        minMonthlyBudget: 100,
        maxMonthlyBudget: 650,
        hasPets: true,
        isSmoker: false,
        isReligionImportant: false,
        isDietImportant: true,
        hasHomeToShare: false
    },
    {
        username: "QWERTYworker",
        gender: "Male",
        birthYear: 1987,
        status: "Single",
        minMonthlyBudget: 2200,
        maxMonthlyBudget: 3550,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Rattata",
        gender: "Female",
        birthYear: 1988,
        status: "Single",
        minMonthlyBudget: 700,
        maxMonthlyBudget: 1250,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "Sierra",
        gender: "Female",
        birthYear: 1945,
        status: "Single",
        minMonthlyBudget: 800,
        maxMonthlyBudget: 1150,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "TooFriendly",
        gender: "Male",
        birthYear: 1970,
        status: "Single",
        minMonthlyBudget: 700,
        maxMonthlyBudget: 1050,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "UltimateRoomie123",
        gender: "Other",
        birthYear: 1996,
        status: "Single",
        minMonthlyBudget: 2400,
        maxMonthlyBudget: 2550,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Ventriloquist45",
        gender: "Male",
        birthYear: 1970,
        status: "Existing Group",
        minMonthlyBudget: 900,
        maxMonthlyBudget: 2050,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Wario",
        gender: "Male",
        birthYear: 1991,
        status: "Single",
        minMonthlyBudget: 700,
        maxMonthlyBudget: 1350,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "XenaThePrincess",
        gender: "Female",
        birthYear: 1981,
        status: "Single",
        minMonthlyBudget: 1100,
        maxMonthlyBudget: 3550,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    },
    {
        username: "YogurtFanatic",
        gender: "Male",
        birthYear: 1991,
        status: "Couple With Children",
        minMonthlyBudget: 1450,
        maxMonthlyBudget: 1550,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: true
    },
    {
        username: "Zelda995",
        gender: "Female",
        birthYear: 1995,
        status: "Couple",
        minMonthlyBudget: 700,
        maxMonthlyBudget: 980,
        hasPets: false,
        isSmoker: true,
        isReligionImportant: false,
        isDietImportant: false,
        hasHomeToShare: false
    }
]

export default mockProfiles;
