/**
 * @Author:     Jeff Hatton
 * @Created:    2020.01.12
 *
 * @Description: Const array of mock profiles
 *
 */

import React from 'react';

const mockProfiles = [
    {
        username: "AliceinWonderLand",
        gender: "Female",
        age: 13,
        status: "Single",
        minRent: 200,
        maxRent: 550,
        pet: false,
        smoke: false,
        religion: false,
        diet: false,
    },
    {
        username: "Babar",
        gender: "Male",
        age: 30,
        status: "Couple With Children",
        minRent: 2000,
        maxRent: 5500,
        pet: true,
        smoke: true,
        religion: true,
        diet: true,
    },
    {
        username: "CREATINE",
        gender: "Other",
        age: 20,
        status: "Single",
        minRent: 800,
        maxRent: 1200,
        pet: false,
        smoke: true,
        religion: true,
        diet: true,
    },
    {
        username: "DonaldDuck",
        gender: "Male",
        age: 35,
        status: "Single Parent",
        minRent: 500,
        maxRent: 600,
        pet: false,
        smoke: false,
        religion: true,
        diet: true,
    },
    {
        username: "EusticeOfNarnia",
        gender: "Male",
        age: 70,
        status: "Single",
        minRent: 1300,
        maxRent: 2300,
        pet: false,
        smoke: false,
        religion: false,
        diet: true,
    },
    {
        username: "Foxtrot",
        gender: "Other",
        age: 65,
        status: "Couple",
        minRent: 1400,
        maxRent: 1600,
        pet: false,
        smoke: false,
        religion: true,
        diet: false,
    },
    {
        username: "Grinch",
        gender: "Other",
        age: 85,
        status: "Single",
        minRent: 2500,
        maxRent: 3700,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Hydra",
        gender: "Female",
        age: 45,
        status: "Couple With Children",
        minRent: 1200,
        maxRent: 2550,
        pet: true,
        smoke: false,
        religion: false,
        diet: false,
    },
    {
        username: "InnigoMontoya",
        gender: "Male",
        age: 50,
        status: "Single Parent",
        minRent: 300,
        maxRent: 575,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "JamesBond",
        gender: "Male",
        age: 70,
        status: "Single",
        minRent: 200,
        maxRent: 550,
        pet: false,
        smoke: true,
        religion: false,
        diet: true,
    },
    {
        username: "Kirby",
        gender: "Other",
        age: 44,
        status: "Existing Group",
        minRent: 200,
        maxRent: 2550,
        pet: false,
        smoke: false,
        religion: false,
        diet: false,
    },
    {
        username: "Link",
        gender: "Male",
        age: 20,
        status: "Couple",
        minRent: 500,
        maxRent: 700,
        pet: true,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Mario",
        gender: "Male",
        age: 70,
        status: "Single",
        minRent: 900,
        maxRent: 2600,
        pet: false,
        smoke: true,
        religion: true,
        diet: false,
    },
    {
        username: "Nero",
        gender: "Male",
        age: 53,
        status: "Existing Group",
        minRent: 3300,
        maxRent: 6650,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "OddDuck",
        gender: "Female",
        age: 23,
        status: "Single",
        minRent: 400,
        maxRent: 1950,
        pet: false,
        smoke: true,
        religion: true,
        diet: true,
    },
    {
        username: "PlatoInPerson",
        gender: "Male",
        age: 70,
        status: "Single Parent",
        minRent: 100,
        maxRent: 650,
        pet: true,
        smoke: false,
        religion: false,
        diet: true,
    },
    {
        username: "QWERTYworker",
        gender: "Male",
        age: 47,
        status: "Single",
        minRent: 2200,
        maxRent: 3550,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Rattata",
        gender: "Female",
        age: 34,
        status: "Single",
        minRent: 700,
        maxRent: 1250,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Sierra",
        gender: "Female",
        age: 85,
        status: "Single",
        minRent: 800,
        maxRent: 1150,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "TooFriendly",
        gender: "Male",
        age: 51,
        status: "Single",
        minRent: 700,
        maxRent: 1050,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "UltimateRoomie123",
        gender: "Other",
        age: 25,
        status: "Single",
        minRent: 2400,
        maxRent: 2550,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Ventriloquist45",
        gender: "Male",
        age: 63,
        status: "Existing Group",
        minRent: 900,
        maxRent: 2050,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Wario",
        gender: "Male",
        age: 32,
        status: "Single",
        minRent: 700,
        maxRent: 1350,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "XenaThePrincess",
        gender: "Female",
        age: 40,
        status: "Single",
        minRent: 1100,
        maxRent: 3550
    },
    {
        username: "YogurtFanatic",
        gender: "Male",
        age: 32,
        status: "Couple With Children",
        minRent: 1450,
        maxRent: 1550,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    },
    {
        username: "Zelda995",
        gender: "Female",
        age: 28,
        status: "Couple",
        minRent: 700,
        maxRent: 980,
        pet: false,
        smoke: true,
        religion: false,
        diet: false,
    }
]

export default mockProfiles;
